version: "3"
services:
  proxy:
    build: ./proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - explorer
      - api-server

  pigeoncoin:
    image: lukepighetti/pigeoncoin:latest
    restart: always
    volumes:
      - "chain_data:/root/.pigeon"
    environment:
      RPC_ALLOW_IP: "0.0.0.0/0"

  mongo:
    build: ../explorer/db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: explorer_database
    volumes:
      - "database_data:/data/db"

  explorer:
    build: ../explorer/express
    restart: always
    depends_on:
      - mongo
      - pigeoncoin
    environment:
      BACK_URL: /

  bot:
    build: ../bot
    restart: always

  api-server:
    build: ../api-server
    restart: always

  api-collector:
    build: ../api-collector/collector
    restart: always
    depends_on:
      - pigeoncoin
    environment:
      RPC_HOST: pigeoncoin
      FETCH_HISTORICAL_MINUTES: 5
      RTDB_URL: https://pigeoncoin-api.firebaseio.com

  seeder:
    build: ../seeder
    restart: always
    ports:
      - "53:53/udp"
    volumes:
      - "seeder_data:/var/dnsseed"
    environment:
      NS_ADDRESS: seed.pigeoncoin.org
      A_ADDRESS: explorer.pigeoncoin.org
      EMAIL: contact@pigeoncoin.org

volumes:
  chain_data:
  database_data:
  seeder_data:
