version: "3"
services:
  pigeoncoin:
    image: lukepighetti/pigeoncoin:latest
    restart: always
    volumes:
      - "chain_data:/root/.pigeon"
    environment:
      RPC_ALLOW_IP: "0.0.0.0/0"

  collector:
    build: ./collector
    restart: always
    depends_on:
      - pigeoncoin
    environment:
      RPC_HOST: pigeoncoin
      FETCH_HISTORICAL_MINUTES: 5
      RTDB_URL: https://scratch-project-9f138.firebaseio.com

volumes: 
  chain_data:
