version: "3"
services:
  pigeon:
    image: twinkykms/pigeon:explorer
    restart: always
    volumes:
      - "chain_data:/root/.pigeon"
    environment:
      RPC_ALLOW_IP: "0.0.0.0/0"
    ports:
      - "8757:8757"

  mongo:
    build: ../explorer/db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: explorer_database
    volumes:
      - "database_data:/data/db"

  explorer:
    build: ../explorer/pgn-express
    restart: always
    depends_on:
      - mongo
      - pigeon
    environment:
      BACK_URL: /
    ports:
      - "80:3001"

  seeder:
    build: ../seeder
    restart: always
    ports:
      - "53:53/udp"
    volumes:
      - "seeder_data:/var/dnsseed"
    environment:
      NS_ADDRESS: seed.mydomain.org
      A_ADDRESS: vps.mydomain.org
      EMAIL: contact@mydomain.org

volumes:
  chain_data:
  database_data:
  seeder_data:
